version: '3.7'

services:
  pull-image:
    command: docker pull espymur/multilingual_drc_news_chatbot:develop
  scraper-d:
    command: scrapyd
    depends_on:
      -  pull-image
    ports:
      - "6800:6800"
  scrapy-web:
    image: scraper
    command:
    - |
       scrapyd-deploy production
       scrapydweb
    depends_on:
      -  scraper-d
    ports:
      - "5000:5000"
    restart: on-failure
    env_file:
      - ./.env
