version: '3.7'

services:
  scraper-d:
    image: espymur/multilingual_drc_news_chatbot:last
    command: scrapyd
    ports:
      - "6800:6800"
  scrapy-web:
    image: espymur/multilingual_drc_news_chatbot:last
    command:
    - |
       scrapyd-deploy production
       scrapydweb
    depends_on:
      -  scraper-d
    ports:
      - "5000:5000"
    restart: on-failure
    env_file:
      - ./.env
