version: '3.7'

services:
  scraper-d:
    image: scraper
    build:
      context: .
      dockerfile: Dockerfile
    command: scrapyd
    ports:
      - "6800:6800"
  scrapy-web:
    image: scraper
    command:
    - |
       scrapyd-deploy production
       printenv POSTGRES_USER
       printenv POSTGRES_PORT
       scrapydweb
    depends_on:
      -  scraper-d
    ports:
      - "5000:5000"
    restart: on-failure
    env_file:
      - ./.env.docker
