name: Build and Publish Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: mr-smithers-excellent/docker-build-push@v4
    - name: Build and Push Docker image
      run: docker build -t multilingual_drc_news_chatbot .
      with:
        image: ${{ secrets.DOCKERHUB_USERNAME }}/multilingual_drc_news_chatbot
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}