name: Build and Publish Docker Image

on:
  push:
    branches: [ master ]

jobs:

  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Check out code

    - uses: mr-smithers-excellent/docker-build-push@v4
      name: Build and Push Docker image
      with:
        image: espymur/multilingual_drc_news_chatbot
        registry: docker.io
        tag: new
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
