name: Build and Publish Docker Image

on:
  push:
    branches: [ docker-setup ]

jobs:

  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Check out code

    - uses: mr-smithers-excellent/docker-build-push@v4
      name: Build and Push Docker image
      with:
        image: espymur/multilingual_drc_news_chatbot
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: appleboy/ssh-action@master
      name: Executing remote command
      with:
        host: ${{ secrets.HOST_IP_ADDRESS  }}
        USERNAME: ${{ secrets.HOST_USERNAME  }}
        PASSWORD: ${{ secrets.HOST_PASSWORD }}
        TIMEOUT: 5m
        COMMAND_TIMEOUT: 5m
        script: |
          docker pull espymur/multilingual_drc_news_chatbot
          docker run multilingual_drc_news_chatbot