name: Deploy to remote server

on:
  workflow_run:
    workflows: [ Build and Publish Docker Image ]
    types:
      - completed

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Check out code

    - name: Add environment variables to .env
      run: |
        echo '''${{ secrets.DATABASE_CRENDENTIALS_ENV }}''' >> .env
        echo '''${{ secrets.SCRAPY_WEB_CREDENTIALS }}''' >> .env
        cat .env

    - name: Copy files into the server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_IP_ADDRESS  }}
        USERNAME: ${{ secrets.HOST_USER_NAME  }}
        PASSWORD: ${{ secrets.HOST_PASSWORD  }}
        TIMEOUT: 5m
        COMMAND_TIMEOUT: 5m
        source: "."
        target: "/Projects/multilingual_drc_news_chatbot"

    - uses: appleboy/ssh-action@master
      name: Executing remote command
      with:
        host: ${{ secrets.HOST_IP_ADDRESS  }}
        USERNAME: ${{ secrets.HOST_USER_NAME  }}
        PASSWORD: ${{ secrets.HOST_PASSWORD  }}
        TIMEOUT: 30m
        COMMAND_TIMEOUT: 30m
        script: |
          cd /Projects/multilingual_drc_news_chatbot
          docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
          docker-compose up --build -d
