name: Deploy to remote server

on:
  push:
    branches: [ setup-deployment-cluster ]

jobs:

  create-env-file:
    name: Create env file
    runs-on: ubuntu-latest
    env: # env available for all steps of jobs
      ENV_KEY_DEBUG: true
      ENV_KEY_USERNAME: root
    
    steps:
      - uses: actions/checkout@v2

      - uses: iamsauravsharma/create-dotenv@v1.2.1
        with:
          env-prefix: 'ENV_KEY_' # Optional (default: '')
          file-name: '.env.docker' # Optional (default : '.env')
          directory: '.' # Optional (default: '.')
        env: # env available for only this steps
          IS_SERVER: true
          ENV_KEY_USERNAME: admin
          ENV_KEY_API_KEY: USER_API_KEY
          ENV_KEY_SECRET_KEY: secret123
          ENV_KEY_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          ENV_KEY_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          ENV_KEY_POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          ENV_KEY_POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          ENV_KEY_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          ENV_KEY_SERVER_HOST: ${{ secrets.HOST_IP_ADDRESS  }}

  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Check out code

    - name: Zipe repo contents
      run: |
        mkdir ../build
        cp -TR . ../build
        tar -cvf deploy.tar ../build/

    - name: Copy files into the server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_IP_ADDRESS  }}
        USERNAME: ${{ secrets.HOST_USER_NAME  }}
        PASSWORD: ${{ secrets.HOST_PASSWORD  }}
        TIMEOUT: 5m
        COMMAND_TIMEOUT: 5m
        source: "./*"
        target: "multilingual_drc_news_chatbot"

    - uses: appleboy/ssh-action@master
      name: Executing remote command
      with:
        host: ${{ secrets.HOST_IP_ADDRESS  }}
        USERNAME: ${{ secrets.HOST_USER_NAME  }}
        PASSWORD: ${{ secrets.HOST_PASSWORD  }}
        TIMEOUT: 2h
        COMMAND_TIMEOUT: 2h
        script: |
          cd multilingual_drc_news_chatbot
          export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          export POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          export POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
          export POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          export HOST_IP_ADDRESS=${{ secrets.HOST_IP_ADDRESS }}
          docker-compose up --build
