name: Deploy to remote server

on:
  push:
    branches: [ setup-deployment-cluster ]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Check out code

    - name: Create env file
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        envkey_POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        envkey_POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        envkey_SERVER_HOST: ${{ secrets.HOST_IP_ADDRESS  }}
        file-name: '.env.docker'
        directory: '.'

    - name: Zipe repo contents
      run: |
        mkdir ../build
        cp -TR . ../build
        tar -cvf deploy.tar ../build/

    - name: Copy files into the server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_IP_ADDRESS  }}
        USERNAME: ${{ secrets.HOST_USER_NAME  }}
        PASSWORD: ${{ secrets.HOST_PASSWORD  }}
        TIMEOUT: 5m
        COMMAND_TIMEOUT: 5m
        source: "./*"
        target: "multilingual_drc_news_chatbot"

    - uses: appleboy/ssh-action@master
      name: Executing remote command
      with:
        host: ${{ secrets.HOST_IP_ADDRESS  }}
        USERNAME: ${{ secrets.HOST_USER_NAME  }}
        PASSWORD: ${{ secrets.HOST_PASSWORD  }}
        TIMEOUT: 2h
        COMMAND_TIMEOUT: 2h
        script: |
          cd multilingual_drc_news_chatbot
          ls
          docker-compose up --build
